"""``cupli set-hooks`` / ``unset-hooks`` and the in-container hook runner.

Generated shims live at ``<repo>/.git/hooks/<hook-name>`` and contain:

1. The marker line ``# cupli-hook v1`` (read by ``unset-hooks`` to decide
   what it owns).
2. A small bash trampoline that calls back into ``cupli __run-hook__``,
   which iterates the source hook scripts and dispatches each one into the
   target's container (with optional per-script directives).
3. A pure-bash fallback that runs the scripts on the host when ``cupli`` is
   not on ``PATH`` — keeps the hooks usable on CI runners that do not have
   cupli installed.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import TYPE_CHECKING

from cupli.domain.consts import (
    GIT_HOOK_NAMES,
    HOOK_DIRECTIVE_PREFIX,
    HOOK_MARKER,
    HOOKS_MANIFEST_FILE,
    STATE_DIR,
)
from cupli.domain.enums import HookKind
from cupli.domain.errors import CupliError
from cupli.utils.console import debug
from cupli.utils.git import is_git_repo
from cupli.utils.path import create_dir, read_json, write_json, write_text
from cupli.utils.subprocess import run_command

if TYPE_CHECKING:
    from pathlib import Path

    from cupli.core.loader import ResolvedSpace


SHIM_TEMPLATE = """\
#!/usr/bin/env bash
{marker} target={target} hook={hook} service={service}
# Generated by `cupli set-hooks`. Re-run that command to regenerate.
set -euo pipefail

CUPLI_HOOKS_DIR={hooks_dir!r}
CUPLI_HOOK={hook!r}
CUPLI_SPACE_FILE={space_file!r}
CUPLI_DEFAULT_CONTAINER={service!r}
CUPLI_DEFAULT_WORKDIR={workdir!r}

if command -v cupli >/dev/null 2>&1; then
    exec cupli -f "$CUPLI_SPACE_FILE" __run-hook__ \\
        --hooks-dir "$CUPLI_HOOKS_DIR" \\
        --hook "$CUPLI_HOOK" \\
        --default-container "$CUPLI_DEFAULT_CONTAINER" \\
        --default-workdir "$CUPLI_DEFAULT_WORKDIR" \\
        -- "$@"
fi

# Bash fallback: cupli is not on PATH. Run the scripts on the host.
for script in "$CUPLI_HOOKS_DIR/$CUPLI_HOOK"/*.sh; do
    [ -f "$script" ] || continue
    bash "$script" "$@"
done
"""

DIRECTIVE_RE = re.compile(r"^\s*#\s*cupli:\s*(?P<body>.+)$", re.MULTILINE)
DIRECTIVE_KV_RE = re.compile(r"(?P<key>\w+)=(?P<value>\S+)")
PRECOMMIT_CONFIG = ".pre-commit-config.yaml"


# --- discovery -------------------------------------------------------------


@dataclass(frozen=True)
class HookTarget:
    """Discovered target for ``cupli set-hooks``."""

    name: str
    kind: HookKind
    repo_path: Path
    service: str
    workdir: str


def discover_targets(resolved: ResolvedSpace, *, scope: str = "all") -> list[HookTarget]:
    """Discover every git working copy that should receive hook shims.

    Args:
        resolved: a :class:`ResolvedSpace`.
        scope: one of ``apps`` / ``bases`` / ``mounts`` / ``all``.

    Returns:
        Dependency-stable list of :class:`HookTarget`.
    """
    targets: list[HookTarget] = []
    if scope in ("apps", "all"):
        targets.extend(_targets_for_apps(resolved))
    if scope in ("mounts", "all"):
        targets.extend(_targets_for_mounts(resolved))
    if scope in ("bases", "all"):
        targets.extend(_targets_for_bases(resolved))
    return targets


def _targets_for_apps(resolved: ResolvedSpace) -> list[HookTarget]:
    """Build HookTargets for every app with a git working copy."""
    out: list[HookTarget] = []
    for name, app in resolved.space.apps.items():
        path = resolved.apps[name].path
        if not is_git_repo(path):
            continue
        service = app.primary_service_name(name)
        workdir = f"/workspace/{name}"
        out.append(HookTarget(name=name, kind=HookKind.APP, repo_path=path, service=service, workdir=workdir))
    return out


def _targets_for_mounts(resolved: ResolvedSpace) -> list[HookTarget]:
    """Build HookTargets for every mount with a git working copy."""
    out: list[HookTarget] = []
    for name, mount in resolved.space.mounts.items():
        path = resolved.mounts[name].path
        if not is_git_repo(path):
            continue
        service = mount.hosted_in[0]
        workdir = resolved.mounts[name].vars["MOUNT_EXEC_PATH"]
        out.append(HookTarget(name=name, kind=HookKind.MOUNT, repo_path=path, service=service, workdir=workdir))
    return out


def _targets_for_bases(resolved: ResolvedSpace) -> list[HookTarget]:
    """Build HookTargets for every base with a git working copy.

    Bases pick the first app that inherits from them as the host service.
    """
    out: list[HookTarget] = []
    inheritance = _base_to_first_app(resolved)
    for name in resolved.space.bases:
        path = resolved.bases[name].path
        if not is_git_repo(path):
            continue
        host_app = inheritance.get(name)
        if host_app is None:
            continue
        service = resolved.space.apps[host_app].primary_service_name(host_app)
        workdir = f"/workspace/{name}"
        out.append(HookTarget(name=name, kind=HookKind.BASE, repo_path=path, service=service, workdir=workdir))
    return out


def _base_to_first_app(resolved: ResolvedSpace) -> dict[str, str]:
    """Map each base name to the first app that inherits from it."""
    out: dict[str, str] = {}
    for app_name, app in resolved.space.apps.items():
        for base_name in app.bases:
            out.setdefault(base_name, app_name)
    return out


# --- install / uninstall ---------------------------------------------------


@dataclass
class HooksManifest:
    """Persisted record of installed shims."""

    installed: list[dict[str, str]]
    """Each entry: ``{target, hook, path}``."""


@dataclass
class HooksReport:
    """Outcome of ``install_hooks`` / ``uninstall_hooks``."""

    installed: list[str]
    skipped: list[str]
    conflicts: list[str]
    removed: list[str]


def install_hooks(
    resolved: ResolvedSpace,
    hooks_dir: Path,
    *,
    scope: str = "all",
    targets_filter: tuple[str, ...] = (),
    force: bool = False,
) -> HooksReport:
    """Generate shims for every selected target and every available hook.

    Args:
        resolved: a :class:`ResolvedSpace`.
        hooks_dir: absolute path to the user-authored hooks directory.
        scope: passed to :func:`discover_targets`.
        targets_filter: when non-empty, restrict to these target names.
        force: overwrite foreign hooks instead of raising ``E024``.

    Returns:
        :class:`HooksReport` with per-shim outcomes.
    """
    targets = _select(discover_targets(resolved, scope=scope), targets_filter)
    available_hooks = _available_hook_names(hooks_dir)
    report = HooksReport(installed=[], skipped=[], conflicts=[], removed=[])
    manifest = _load_manifest(resolved)

    for target in targets:
        if (target.repo_path / PRECOMMIT_CONFIG).exists() and not force:
            report.conflicts.append(f"{target.name}: {PRECOMMIT_CONFIG} present (use --force)")
            continue
        for hook in available_hooks:
            _install_one(target, hook, hooks_dir, resolved, manifest, report, force=force)

    _save_manifest(resolved, manifest)
    return report


def uninstall_hooks(
    resolved: ResolvedSpace,
    *,
    scope: str = "all",
    targets_filter: tuple[str, ...] = (),
) -> HooksReport:
    """Remove every shim previously installed by cupli.

    User-authored hooks (missing the marker) are left alone.
    """
    targets = _select(discover_targets(resolved, scope=scope), targets_filter)
    report = HooksReport(installed=[], skipped=[], conflicts=[], removed=[])
    manifest = _load_manifest(resolved)

    for target in targets:
        hooks_dir = target.repo_path / ".git" / "hooks"
        if not hooks_dir.is_dir():
            continue
        for hook in GIT_HOOK_NAMES:
            shim_path = hooks_dir / hook
            if not shim_path.exists():
                continue
            if not _is_cupli_shim(shim_path):
                continue
            shim_path.unlink()
            report.removed.append(f"{target.name}:{hook}")
            manifest.installed = [
                entry for entry in manifest.installed if not (entry["target"] == target.name and entry["hook"] == hook)
            ]

    _save_manifest(resolved, manifest)
    return report


# --- hook runner (invoked by the shim) -------------------------------------


def run_hook(
    resolved: ResolvedSpace,
    *,
    hooks_dir: Path,
    hook: str,
    default_container: str,
    default_workdir: str,
    extra_args: list[str],
) -> int:
    """Iterate scripts under ``hooks_dir/hook/*.sh`` and dispatch each.

    Per-script first-line directives (``# cupli: container=node workdir=/app``)
    override the default container/workdir. Each script is fed to
    ``docker compose exec -T <container> bash -c <content>``.
    """
    from cupli.services.compose_service import build_argv, make_plan

    if not hooks_dir.is_dir():
        debug(f"hooks dir missing: {hooks_dir}")
        return 0
    scripts_dir = hooks_dir / hook
    if not scripts_dir.is_dir():
        debug(f"no scripts for hook {hook}")
        return 0

    plan = make_plan(resolved)
    for script in sorted(scripts_dir.iterdir()):
        if not script.is_file():
            continue
        container, workdir, shell = _parse_directive(script, default_container, default_workdir)
        content = script.read_text(encoding="utf-8")
        exec_args = ["exec", "-T"]
        if workdir:
            exec_args.extend(["--workdir", workdir])
        exec_args.extend([container, shell, "-c", content, "--", *extra_args])
        argv = build_argv(plan, exec_args)
        completed = run_command(argv, cwd=resolved.space_dir, check=False)
        if completed.returncode != 0:
            return completed.returncode
    return 0


_DEFAULT_HOOK_SHELL = "bash"
"""Default in-container interpreter for hook scripts; override with ``shell=`` directive."""


def _parse_directive(
    script: Path,
    default_container: str,
    default_workdir: str,
) -> tuple[str, str, str]:
    """Extract ``container``, ``workdir``, ``shell`` overrides from the script header.

    Recognised keys in the ``# cupli: …`` first-line directive:

    - ``container=<svc>`` — exec into a different compose service.
    - ``workdir=<path>`` — working directory inside the container.
    - ``shell=<name>`` — interpreter (``bash`` by default; pick ``sh`` for
      busybox-only images like alpine).
    """
    container = default_container
    workdir = default_workdir
    shell = _DEFAULT_HOOK_SHELL
    head = "\n".join(script.read_text(encoding="utf-8").splitlines()[:5])
    match = DIRECTIVE_RE.search(head)
    if match is None:
        return container, workdir, shell
    for kv in DIRECTIVE_KV_RE.finditer(match.group("body")):
        key, value = kv.group("key"), kv.group("value")
        if key == "container":
            container = value
        elif key == "workdir":
            workdir = value
        elif key == "shell":
            shell = value
    return container, workdir, shell


# --- helpers ---------------------------------------------------------------


def build_shim(
    target: HookTarget,
    hook: str,
    *,
    hooks_dir: Path,
    space_file: Path,
) -> str:
    """Build the bash shim body for ``(target, hook)``."""
    return SHIM_TEMPLATE.format(
        marker=HOOK_MARKER,
        target=target.name,
        hook=hook,
        service=target.service,
        workdir=target.workdir,
        hooks_dir=str(hooks_dir),
        space_file=str(space_file),
    )


def _available_hook_names(hooks_dir: Path) -> list[str]:
    """Return every git hook directory found under ``hooks_dir``."""
    if not hooks_dir.is_dir():
        return []
    return sorted(entry.name for entry in hooks_dir.iterdir() if entry.is_dir() and entry.name in GIT_HOOK_NAMES)


def _select(targets: list[HookTarget], wanted: tuple[str, ...]) -> list[HookTarget]:
    """Optionally restrict ``targets`` to the named subset."""
    if not wanted:
        return targets
    wanted_set = set(wanted)
    return [target for target in targets if target.name in wanted_set]


def _install_one(
    target: HookTarget,
    hook: str,
    hooks_dir: Path,
    resolved: ResolvedSpace,
    manifest: HooksManifest,
    report: HooksReport,
    *,
    force: bool,
) -> None:
    """Write one shim file; respect markers / ``force`` semantics."""
    git_hooks = target.repo_path / ".git" / "hooks"
    create_dir(git_hooks)
    shim_path = git_hooks / hook

    space_file = _space_file_for(resolved)
    body = build_shim(target, hook, hooks_dir=hooks_dir, space_file=space_file)

    if shim_path.exists() and not _is_cupli_shim(shim_path) and not force:
        report.conflicts.append(f"{target.name}:{hook} (foreign hook; --force to overwrite)")
        return

    write_text(shim_path, body)
    shim_path.chmod(0o755)
    report.installed.append(f"{target.name}:{hook}")
    manifest.installed.append(
        {"target": target.name, "hook": hook, "path": str(shim_path)},
    )


def _space_file_for(resolved: ResolvedSpace) -> Path:
    """Locate the space file inside ``resolved.space_dir`` (best effort)."""
    candidates = list(resolved.space_dir.glob("*.cupli.yaml")) + list(
        resolved.space_dir.glob("*.cupli.yml"),
    )
    if candidates:
        return candidates[0]
    return resolved.space_dir / "space.cupli.yaml"


def _is_cupli_shim(path: Path) -> bool:
    """Return True when ``path`` starts with the cupli marker line."""
    try:
        head = path.read_text(encoding="utf-8").splitlines()[:2]
    except (OSError, UnicodeDecodeError):
        return False
    return any(line.startswith(HOOK_MARKER) for line in head)


def _manifest_path(resolved: ResolvedSpace) -> Path:
    """Absolute path of the per-space hooks manifest."""
    from pathlib import Path as _Path

    locals_path = resolved.space_vars["LOCALS_PATH"]
    state_dir = _Path(locals_path) / resolved.space.name / STATE_DIR
    create_dir(state_dir)
    return state_dir / HOOKS_MANIFEST_FILE


def _load_manifest(resolved: ResolvedSpace) -> HooksManifest:
    """Load the manifest or return an empty one when missing."""
    path = _manifest_path(resolved)
    if not path.exists():
        return HooksManifest(installed=[])
    data = read_json(path)
    if not isinstance(data, dict) or not isinstance(data.get("installed"), list):
        return HooksManifest(installed=[])
    return HooksManifest(installed=list(data["installed"]))


def _save_manifest(resolved: ResolvedSpace, manifest: HooksManifest) -> None:
    """Persist the manifest."""
    write_json(_manifest_path(resolved), {"installed": manifest.installed})


def list_target_names(resolved: ResolvedSpace) -> list[str]:
    """Return every discoverable target name; used by CLI typo suggestions."""
    return [target.name for target in discover_targets(resolved)]


def hook_target_or_raise(resolved: ResolvedSpace, name: str) -> HookTarget:
    """Look up a target by name or raise ``E023``."""
    for target in discover_targets(resolved):
        if target.name == name:
            return target
    raise CupliError("E023", target=name)


__all__ = (
    "HOOK_DIRECTIVE_PREFIX",
    "HookTarget",
    "HooksManifest",
    "HooksReport",
    "build_shim",
    "discover_targets",
    "hook_target_or_raise",
    "install_hooks",
    "list_target_names",
    "run_hook",
    "uninstall_hooks",
)
