"""Project-wide constants.

Constants are organised into named blocks:
- Logger / version / patterns shared between parser, validator, and CLI.
- Default directory and file names for the on-disk space layout.
- State-directory file names under ``.locals/<space>/state/``.
- Hook-shim marker and supported git hook names.
- Variable-interpolation regex used by the env resolver.
- Docker-compose version floor.
"""

import re
from typing import Final, Literal

LOGGER_NAME: Final[str] = "CUPLI"
"""Default logger name."""
DEFAULT_MIN_VERSION: Final[str] = "0.1.0"
"""Default minimum required version of cupli package."""
DEFAULT_MAX_VERSION: Final[str] = "*"
"""Default maximum required version of cupli package (wildcard)."""
DEFAULT_SCHEMA_VERSION: Final[Literal[1]] = 1
"""Default schema_version when the space file omits the field."""
NAME_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
"""Docker-like name pattern: starts with a letter, alnum/underscore/hyphen tail."""
TAG_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-z][a-z0-9_-]*$")
"""Tag pattern: lowercase letters/digits/underscore/hyphen, first char alpha."""
VERSION_PATTERN: Final[re.Pattern[str]] = re.compile(r"^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$")
"""Semver-ish pattern (supports ``*`` wildcard for any component)."""
CUPLI_SPACE_FILE_PATTERN: Final[re.Pattern[str]] = re.compile(r"^(?:.+\.)?cupli\.ya?ml$")
"""Filename pattern for auto-detected space files in the current directory."""
VAR_REF_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"\$\$"
    r"|\$\{(?P<name>[A-Za-z_][A-Za-z0-9_]*)(?::-(?P<default>[^}]*))?\}"
    r"|\$(?P<bare>[A-Za-z_][A-Za-z0-9_]*)",
)
"""Pattern recognised by the env resolver.

Matches ``${VAR}``, ``${VAR:-default}`` and bare ``$VAR`` references; ``$$`` is
an escape for a literal ``$`` (docker-compose convention)."""

DEFAULT_APPS_DIR: Final[str] = "src/apps"
"""Default folder name for app checkouts (relative to ``SPACE_PATH``)."""
DEFAULT_BASES_DIR: Final[str] = "src/bases"
"""Default folder name for base-app checkouts (relative to ``SPACE_PATH``)."""
DEFAULT_MOUNTS_DIR: Final[str] = "src/mounts"
"""Default folder name for mount checkouts (relative to ``SPACE_PATH``)."""
DEFAULT_LOCALS_DIR: Final[str] = ".locals"
"""Default folder name for per-space local data (state, overrides, caches)."""
DEFAULT_ENV: Final[str] = ".env"
"""Default per-target env-file name."""
DEFAULT_GIT_DIR: Final[str] = ".git"
"""Folder name that signals an existing git working copy."""
DEFAULT_COMPOSE_FILE_NAMES: Final[tuple[str, ...]] = ("docker-compose.yml", "docker-compose.yaml")
"""Filenames auto-detected as the per-app compose file when ``composes:`` is empty."""

UNNAMED_VAR_PREFIX: Final[str] = "__UNNAMED_CUPLI_VAR"
"""Prefix of synthetic variable names used by the legacy env resolver."""

STATE_DIR: Final[str] = "state"
"""Subdirectory under ``.locals/<space>/`` carrying cache/lock/manifest files."""
OVERRIDE_PRE_FILE: Final[str] = "docker-compose.pre.yml"
"""Generated compose override merged BEFORE user compose files (defaults)."""
OVERRIDE_POST_FILE: Final[str] = "docker-compose.post.yml"
"""Generated compose override merged AFTER user compose files (forced)."""
OVERRIDE_ENV_FILE: Final[str] = "override.env"
"""Generated ``--env-file`` written by the compose service."""
OVERRIDE_INLINE_FILE: Final[str] = "docker-compose.inline.yml"
"""Generated compose file holding services declared inline under ``apps.<x>.services``."""
AUTO_GENERATED_HEADER: Final[str] = (
    "# =====================================================================\n"
    "# AUTO-GENERATED by cupli. DO NOT EDIT.\n"
    "# This file is regenerated on every cupli invocation.\n"
    "# Edit space.cupli.yaml instead.\n"
    "# =====================================================================\n"
)
"""Hash-prefixed banner prepended to every cupli-generated YAML/.env file."""
VARS_CACHE_FILE: Final[str] = "vars.json"
"""Last resolved variable map (powers the fast ``cupli vars`` path)."""
INPUT_HASH_FILE: Final[str] = "cache.json"
"""Hashes of inputs that affect override regeneration."""
HOOKS_MANIFEST_FILE: Final[str] = "hooks-manifest.json"
"""List of hook shims installed by ``cupli set-hooks``."""
LOCK_FILE: Final[str] = "lock"
"""Per-space pid lockfile for serialised lifecycle invocations."""
EVENTS_LOG_FILE: Final[str] = "events.log"
"""Per-space append-only log of lifecycle events."""

HOOK_MARKER: Final[str] = "# cupli-hook v1"
"""First-line marker stamped on shims generated by ``cupli set-hooks``."""
HOOK_DIRECTIVE_PREFIX: Final[str] = "# cupli:"
"""Per-script directive prefix (``# cupli: container=<svc> workdir=<path>``)."""

GIT_HOOK_NAMES: Final[tuple[str, ...]] = (
    "applypatch-msg",
    "pre-applypatch",
    "post-applypatch",
    "pre-commit",
    "pre-merge-commit",
    "prepare-commit-msg",
    "commit-msg",
    "post-commit",
    "pre-rebase",
    "post-checkout",
    "post-merge",
    "pre-push",
    "pre-receive",
    "update",
    "proc-receive",
    "post-receive",
    "post-update",
    "reference-transaction",
    "push-to-checkout",
    "pre-auto-gc",
    "post-rewrite",
    "sendemail-validate",
    "fsmonitor-watchman",
    "p4-changelist",
    "p4-prepare-changelist",
    "p4-post-changelist",
    "p4-pre-submit",
    "post-index-change",
)
"""All 28 git hook names supported by ``cupli set-hooks``."""

DOCKER_COMPOSE_MIN_VERSION: Final[str] = "2.20"
"""Minimum docker compose v2 version cupli supports."""

COMMANDS_PANEL_TITLE: Final[str] = "Workspace commands"
"""Rich help-panel title for user-declared ``commands:`` shortcuts."""

# --- Rich help-panel titles -------------------------------------------------

PANEL_LIFECYCLE: Final[str] = "Lifecycle"
"""Help panel for up/down/restart/stop/ps/logs/build/pull/compose/watch."""
PANEL_EXEC: Final[str] = "Container interaction"
"""Help panel for exec/run/shell/with."""
PANEL_WORKSPACE: Final[str] = "Workspace"
"""Help panel for init/workspace/space subapps."""
PANEL_DISCOVERY: Final[str] = "Discovery"
"""Help panel for env/config/explain/--list/version/dashboard/graph/stats."""
PANEL_INTEGRATIONS: Final[str] = "Integrations"
"""Help panel for hooks/mounts/git subapps + completion/upgrade-config."""
